### ISSUE TITLE
Unix: Return error when trying to open a device file

### ISSUE THREAD

**Issue by ilai-deutel** [ilai-deutel/kibi#166]
`kibi /dev/random` should fail with an error message

[std](https://doc.rust-lang.org/std/index.html)::[os](https://doc.rust-lang.org/std/os/index.html)::[unix](https://doc.rust-lang.org/std/os/unix/index.html)::[fs](https://doc.rust-lang.org/std/os/unix/fs/index.html)::[FileTypeExt](https://doc.rust-lang.org/std/os/unix/fs/trait.FileTypeExt.html#) can be used to determine the file type.

**Comment by ilmanzo** [comment]
Hello, I’m quite new to Rust but I wish to try with this issue 🙂

**Comment by ilai-deutel** [comment]
@ilmanzo Great, thank you! Let me know if you have any questions
