### ISSUE TITLE
win10，config.ini and Syntax highlighting do not take effect

### ISSUE THREAD

**Issue by miaomiao1992** [ilai-deutel/kibi#232]
**Describe the bug**

i install the kibi via command --cargo install kibi.

my os is win10,and i put config files at the location of "C:\Users\Administrator\AppData\Kibi\syntax.d" which is according to the guide(A configuration file can be located at %APPDATA%\Kibi\config.ini.).

but when i open the build.rs ,the Syntax highlighting does not take effect.

**To Reproduce**

![222](https://user-images.githubusercontent.com/59018630/236145172-1e55dcef-8511-46d0-aab5-e26085ebfb61.png)

**Expected behavior**

**Screenshots**

![1](https://user-images.githubusercontent.com/59018630/236144302-909d34ca-dceb-4cb1-9438-90d7bc9c5b00.png)

**System information**:
 -  OS: win10 
 - Rust version (output of `rustc --version`):rustc 1.68.2 (9eb3afe9e 2023-03-27)
- Kibi version (output of `kibi --version`):v0.2.2

**Additional context**

**Comment by miaomiao1992** [comment]
i don't know which is right?

1、Syntax highlighting configuration files can be located at %APPDATA%\Kibi\syntax.d\<file_name>.ini.

2、A configuration file can be located at %APPDATA%\Kibi\config.ini.

**Comment by ilai-deutel** [comment]
Hi @miaomiao1992,

`%APPDATA%\Kibi\config.ini` is used for the general Kibi configuration file. Syntax highlighting configuration files such as `bash.ini` must be placed in the `%APPDATA%\Kibi\syntax.d` folder
