### ISSUE TITLE
Kibi on Termux fails to start

### ISSUE THREAD

**Issue by Woomy4680-exe** [ilai-deutel/kibi#87]
**Describe the bug**
When I start kibi on termux, i returns a "Permission Denied" error (as you can see in the sreenshot )
Note: I have all permissions required to edit the file.

**To Reproduce**
Use `pkg install kibi` and try to open a file. Note: same error is given if kibi is installed with `cargo install kibi`

**Expected behavior**
Open editor and start editing the file

**Screenshots**

**System information**:
 -  OS: Termux (nonroot)
 - Rust version: 1.49
- Kibi version : V0.2.1

Thanks for this really good work, Woomy

**Comment by Woomy4680-exe** [comment]
Seems i can't upload screenshot.

Here is the console output:

```
Error: IO(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

**Comment by ilai-deutel** [comment]
Thank you for reporting this, I can reproduce the issue. I think that either the main config file or one of the syntax highlighting files are not readable, which causes the issue.

I'll look into it shortly.

**Comment by ilai-deutel** [comment]
It should be fixed in master, seems like it was related to an Android security policy! I will create a release soon and update the termux package.

**Comment by ilai-deutel** [comment]
@all-contributors please add @Woomy4680-exe for bug

**Comment by Woomy4680-exe** [comment]
Hey! Thanks for this fix !
